# This rule is not used by the project nomad-enterprise-operator itself.
# It is provided to allow the cluster admin to help manage permissions for users.
#
# Grants permissions to create, update, and delete resources within the nomad.hashicorp.com.
# This role is intended for users who need to manage these resources
# but should not control RBAC or manage permissions for others.

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: nomad-enterprise-operator
    app.kubernetes.io/managed-by: kustomize
  name: nomadcluster-editor-role
rules:
- apiGroups:
  - nomad.hashicorp.com
  resources:
  - nomadclusters
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - nomad.hashicorp.com
  resources:
  - nomadclusters/status
  verbs:
  - get
